insert into SUJET (idSujet,motClef) values(21,'homéopathie')
insert into SUJET (idSujet,motClef) values(22,'systèmique')
insert into SUJET (idSujet,motClef) values(23,'épidémiologie')
insert into SUJET (idSujet,motClef) values(24,'primaire')
insert into SUJET (idSujet,motClef) values(25,'didactique')
insert into SUJET (idSujet,motClef) values(26,'psychanalyse')
insert into SUJET (idSujet,motClef) values(27,'quantique')
insert into SUJET (idSujet,motClef) values(28,'parallèle')
insert into SUJET (idSujet,motClef) values(29,'efficacité')
insert into SUJET (idSujet,motClef) values(30,'hypergraphs')
insert into SUJET (idSujet,motClef) values(31,'Big')
insert into SUJET (idSujet,motClef) values(32,'heterogeneous')
insert into SUJET (idSujet,motClef) values(33,'neurodecision trees')
insert into SUJET (idSujet,motClef) values(34,'neural')
insert into SUJET (idSujet,motClef) values(35,'recurrent')
insert into SUJET (idSujet,motClef) values(36,'convolution')
select * from dual;