insert all
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(1,'La pataphysique homéopathique et ses bienfaits connus','bla-bla','tiny-url', 1)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(2,'L’approche systémique en pataphysiologie','bla-bla','tiny-url', 1)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(3,'Revue critique des théories pataphydiques en épidémiologie','bla-bla','tiny-url', 1)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(4,'Enseignement de la pataphysique au primaire','bla-bla','tiny-url', 2)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(5,'Vers une nouvelle didactique de la pataphysique','bla-bla','tiny-url', 2)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(6,'Comparaison des cours de pataphysique et de psychanalyse','bla-bla','tiny-url', 2)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(7,'Education et pataphysique : un nouveau contrat social','bla-bla','tiny-url', 3)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(8,'Pataphysique : science, philosophie et escroquerie','bla-bla','tiny-url', 3)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(9,'Pate-à-sel et pataphysique : construire l enseignement du futur','bla-bla','tiny-url', 3)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(10,'Vers des outils pataphysiques adaptés : un état de l art','bla-bla','tiny-url', 4)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(11,'Le calendrier pataphysique, une approche holistique ','bla-bla','tiny-url', 4)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(12,'Des outils imaginaires pour des solutions imaginaires','bla-bla','tiny-url', 4)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(13,'NewSQL : une approche relationelle solide pour une analyse de graphes robuste','bla-bla','tiny-url', 5)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(14,'Book embedding, réduction des espaces de recherche dans l analyse de graphes complexes','bla-bla','tiny-url', 5)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(15,'Fonctions noyaux de graphes : extraction de caracteristiques dans des espaces infinis','bla-bla','tiny-url', 5)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(16,'Deep learning : une composition de problèmes convexes et ses solutions alternatives','bla-bla','tiny-url', 6)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(17,'L influence des modèles distribués sur les langages de programmation','bla-bla','tiny-url', 6)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(18,'Cryptage à faible consommation d énergie pour les table de partition dans les architectures distribueés','bla-bla','tiny-url', 6)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(19,'De l exploration des arbres suffixes','bla-bla','tiny-url', 7)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(20,'Émulation de la tolérance aux pannes byzantines et des protocoles','bla-bla','tiny-url', 7)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(21,'Analyse de la vérification du modèle et de la redondance','bla-bla','tiny-url', 7)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(22,'Abyss : la singularité, une question de couches ?','bla-bla','tiny-url', 8)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(23,'L influence de la théorie aléatoire sur l ingénierie du logiciel d autoapprentissage','bla-bla','tiny-url', 8)
	into SOUMISSION (noSoumission,titre,resume,corps, idTrack) values(24,'Un cas pour la loi de Moore','bla-bla','tiny-url', 8)
select * from dual;
