insert into COPRESIDENT (idComite,idChercheur) values(11,1)
insert into COPRESIDENT (idComite,idChercheur) values(11,4)
insert into COPRESIDENT (idComite,idChercheur) values(12,2)
insert into COPRESIDENT (idComite,idChercheur) values(12,3)
insert into COPRESIDENT (idComite,idChercheur) values(13,3)
insert into COPRESIDENT (idComite,idChercheur) values(13,2)
insert into COPRESIDENT (idComite,idChercheur) values(14,8)
insert into COPRESIDENT (idComite,idChercheur) values(14,4)
insert into COPRESIDENT (idComite,idChercheur) values(15,16)
insert into COPRESIDENT (idComite,idChercheur) values(15,10)
insert into COPRESIDENT (idComite,idChercheur) values(16,6)
insert into COPRESIDENT (idComite,idChercheur) values(16,8)
insert into COPRESIDENT (idComite,idChercheur) values(17,7)
insert into COPRESIDENT (idComite,idChercheur) values(17,10)
insert into COPRESIDENT (idComite,idChercheur) values(18,8)
insert into COPRESIDENT (idComite,idChercheur) values(18,9)
select * from dual;