insert all
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(1,'Deslisle','Xavier','UQAM')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(2,'Capitaine','Milène','UQAM')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(3,'Wouawad','Hajdi','U. de Provence')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(4,'Dutoit','René','SAP')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(5,'Strumpf','Helmut','Volkswagen')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(6,'Gregoriano','Bruno','U. de Bologna')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(7,'Missoukov','Vladimir','U. de Bologna')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(8,'Nakamura','Tiropito','Sony')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(9,'Blaassen','Wilem','Phillips')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(10,'Fred','O’Henry','U. of Washington')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(11,'Nora','Olssen','Ericsson')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(12,'Jeyong','Park','Samsung')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(13,'Rakesh','Gupta','SAP India')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(14,'Ian','Holmes','Birkbeck College')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(15,'Dolores','Cruz','U. de Madrid')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(16,'Tadeusz','Hvostovski','U. of Krakov')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(17,' Flanagan','David','U. of Krakov')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(18,' Nassar','Nazih','U. of Krakov')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(19,'Mario','Luigi','U. de Madrid')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(20,'Trahan','Terry','U. of Washington')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(21,'Auberjonois','Aubin','U. de Madrid')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(22,'Jaeger','Patrick' ,'Sony')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(23,' Wan','Chang','Sony')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(24,'Pépin','Marsilius','U. of Washington')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(25,'Ribeiro','Davi' ,'U. de Rio de Janeiro')
	into CHERCHEUR (idChercheur,nom,prenom,adresse) values(26,'Davison','Katherine','Birkbeck College')
select * from dual;