insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(1,'Deslisle','Xavier','UQAM')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(2,'Capitaine','Milène','UQAM')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(3,'Wouawad','Hajdi','U. de Provence')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(4,'Dutoit','René','SAP')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(5,'Strumpf','Helmut','Volkswagen')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(6,'Gregoriano','Bruno','U. de Bologna')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(7,'Missoukov','Vladimir','U. de Bologna')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(8,'Nakamura','Tiropito','Sony')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(9,'Blaassen','Wilem','Phillips')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(10,'Fred','O’Henry','U. of Washington')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(11,'Nora','Olssen','Ericsson')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(12,'Jeyong','Park','Samsung')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(13,'Rakesh','Gupta','SAP India')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(14,'Ian','Holmes','Birkbeck College')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(15,'Dolores','Cruz','U. de Madrid')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(16,'Tadeusz','Hvostovski','U. of Krakov')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(17,' Flanagan','David','U. of Krakov')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(18,' Nassar','Nazih','U. of Krakov')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(19,'Mario','Luigi','U. de Madrid')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(20,'Trahan','Terry','U. of Washington')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(21,'Auberjonois','Aubin','U. de Madrid')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(22,'Jaeger','Patrick' ,'Sony')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(23,' Wan','Chang','Sony')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(24,'Pépin','Marsilius','U. of Washington')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(25,'Ribeiro','Davi' ,'U. de Rio de Janeiro')
insert into CHERCHEUR (idChercheur,nom,prenom,adresse) values(26,'Davison','Katherine','Birkbeck College')
select * from dual;